# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/pavel/.local/share/ue/Linux_Unreal_Engine_5.4.4
GAMEPROJECTFILE =/home/pavel/projects/ue/ue5_TinyQuest/TinyQuest.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	TinyQuest-Linux-DebugGame  \
	TinyQuest-Linux-Shipping  \
	TinyQuest \
	TinyQuestEditor-Linux-DebugGame  \
	TinyQuestEditor-Linux-Shipping  \
	TinyQuestEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TinyQuestEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TinyQuestEditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

TinyQuest-Linux-DebugGame:
	 $(PROJECTBUILD) TinyQuest Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TinyQuest-Linux-Shipping:
	 $(PROJECTBUILD) TinyQuest Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TinyQuest:
	 $(PROJECTBUILD) TinyQuest Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

TinyQuestEditor-Linux-DebugGame:
	 $(PROJECTBUILD) TinyQuestEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TinyQuestEditor-Linux-Shipping:
	 $(PROJECTBUILD) TinyQuestEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TinyQuestEditor:
	 $(PROJECTBUILD) TinyQuestEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
